### ISSUE TITLE
"Cannot find module" after Electron build.

### ISSUE THREAD

**Issue by mvbn** [aadsm/jschardet#35]
Your library is great. But there is an issue, when I start the app compiled with Electron, I have an error message. I had a similar problem with others libraries like JSZip, js-xlsx, etc, but I found the way to use them also on Electron builds, unfortunately I wasn't lucky with jschardet.
Please can you have a look? Thanks!

Here a sample minimal project (to reproduce the problem): https://www.dropbox.com/sh/15udlyrx06u858i/AADtWNmy1WSryrMI723u4q2fa?dl=0

Uncaught Exception:
Error: Cannot find module './src'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/dev/Desktop/App/releases/App-darwin-x64/App.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dev/Desktop/App/releases/App-darwin-x64/App.app/Contents/Resources/app/node_modules/jschardet/index.js:1:173)
    at Object.<anonymous> (/Users/dev/Desktop/App/releases/App-darwin-x64/App.app/Contents/Resources/app/node_modules/jschardet/index.js:2:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by mvbn** [comment]
Using electron-builder instead of electron-packager, it works! ;)

**Comment by aadsm** [comment]
@mvbn I'm happy you were able to find the solution! Would you like to write a blog post or something about it that I can link to? Thank you.

**Comment by mvbn** [comment]
@aadsm I attach here the "electron-builder" sample version (some info on the "readme.md" file). I didn't follow special operations to have the library working, it just properly work if builded with electron-builder instead of electron-packager. Thanks for your great library!

[sample-ok-with-electron-builder.zip](https://github.com/aadsm/jschardet/files/950754/sample-ok-with-electron-builder.zip)

PS: Ahah, it's a small world. ;)
